### ISSUE TITLE
RFC: misleading file/folder selection behaviour

### ISSUE THREAD

**Issue by marcoms** [afollestad/cabinet#85]
I believe the current, tapping-the-icon-selects behaviour has a few flaws. For example a user can end up tapping the icon repeatedly, expecting cabinet to open it, whereas it is only being selected instead. This issue is much more apparent in grid mode.

A friend only recently had this same problem, asking me how to open things in the cabinet app. I simply changed it to list mode and explained the behaviour, which is not ideal on a tablet...

I suggest only allowing selections via long pressing, whilst subsequent selections can be made through taps just the same.

**Comment by Sniperfox47** [comment]
To be blunt I think the current behavior works amazing. It works exactly the same way the google apps such as gmail and inbox for selection and activation. I always found that apps such as ES made multiple file selections needlessly slow with the long tap and were counterintuitive. The current paradigm in Cabinet was really quick to pick up for me, especially since everything is explained right off the bat in a simple tutorial. No unexpected behavior unlike more complex like ES.

Ekeltho, honestly if anything I think Hangouts should switch to be consistent with the other google apps.
